@startuml
!include .\\Program.puml
!include .\\obj\Debug\net6.0\.NETCoreApp,Version=v6.0.AssemblyAttributes.puml
!include .\\obj\Debug\net6.0\Computation.AssemblyInfo.puml
!include .\\obj\Debug\net6.0\Computation.GlobalUsings.g.puml
@enduml
